"""
Django settings for nlp_app project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-xc^93lja)av-j*po=p&0!9j!7)5s=7_$@2$qv$thupz4doa#tq"

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG berdasarkan environment variable atau default ke False untuk production
import os
from dotenv import load_dotenv

# Load environment variables from .env file jika ada
load_dotenv()

DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Allowed hosts dari environment variable atau default ke domain yang sudah ditentukan
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'nlp.text.analyzer.buyportfolio.my.id,www.nlp.text.analyzer.buyportfolio.my.id,localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "analyzer",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "nlp_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Konfigurasi untuk halaman error kustom
HANDLER404 = 'analyzer.views.custom_404'
HANDLER500 = 'analyzer.views.custom_500'
HANDLER403 = 'analyzer.views.custom_403'

WSGI_APPLICATION = "nlp_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Konfigurasi database dari environment variables
db_engine = os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3')
db_name = os.environ.get('DB_NAME', 'db.sqlite3')

DATABASES = {
    "default": {
        "ENGINE": db_engine,
    }
}

# Konfigurasi khusus untuk SQLite
if db_engine == 'django.db.backends.sqlite3':
    DATABASES['default']['NAME'] = BASE_DIR / db_name
# Konfigurasi untuk MySQL atau database lain
else:
    DATABASES['default'].update({
        "NAME": db_name,
        "USER": os.environ.get('DB_USER', ''),
        "PASSWORD": os.environ.get('DB_PASSWORD', ''),
        "HOST": os.environ.get('DB_HOST', 'localhost'),
        "PORT": os.environ.get('DB_PORT', '3306'),
    })

# Konfigurasi NLTK data
nltk_data_path = os.environ.get('NLTK_DATA', os.path.join(BASE_DIR, 'nltk_data'))
os.environ['NLTK_DATA'] = nltk_data_path


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom error handlers
HANDLER404 = 'analyzer.views.custom_404'
HANDLER500 = 'analyzer.views.custom_500'
HANDLER403 = 'analyzer.views.custom_403'
